### ISSUE TITLE
TwinCAT ADS Error code 1873(Hash table overflow)..

### ISSUE THREAD

**Issue by AnandHegden** [Beckhoff/DeviceManager_ADS_Samples#2]
Hi,I am using TwinCAT 3.0 ADS Communication using for  c++ MFC Application and used TcADs.dll API.while registering the variable getting ADS comm error code 1873(Hash table overflow error)..Please could  know that reason and what are all possible way to solve issue?

**Comment by StephanAv** [comment]
As this doesn't seem related to this library: Please contact the Support your local Beckhoff subsidiary. You can use the [Support form](https://www.beckhoff.com/en-en/support/support-form/index.aspx) on our homepage.
