### ISSUE TITLE
Read TC Revision in GetTcVersion

### ISSUE THREAD

**Issue by maxxie85** [Beckhoff/DeviceManager_ADS_Samples#3]
Is it possible to also read the revision number in the GetTcVersion?

I already tried to add the additional function assuming it was on the next subindex

```C++
int32_t TwinCAT::getTcRevision(uint16_t& revision) 
{
	uint32_t u32_tc_revision_idx = 0x8001 + (m_moduleId << 4);
	u32_tc_revision_idx = (u32_tc_revision_idx << 16) + 4; // Subindex "Revision version"

	uint32_t n_bytesRead = 0;
	return m_adsClient.AdsReadReq(MDP_IDX_GRP, u32_tc_revision_idx, sizeof(revision), &revision, &n_bytesRead);
}
```

However this results in the Ads-Error 0xECA60102

**Comment by hANSIc99** [comment]
At sub index 4 is the AmsNetId. Here you can find the information model:
https://infosys.beckhoff.com/content/1033/devicemanager/263030539.html 

Anyway, I will check if/how it is possible to read the revision.

**Comment by maxxie85** [comment]
Oh that page helps a lot. On first glance it looks like I need to read sub index 12.
Going to test it tomorrow.

**Comment by maxxie85** [comment]
It look like sub index 12 is indeed the TwinCAT revision.
